<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" width = 450>

Numpy es la biblioteca fundamental para computación científica. Se basa en un objeto array n-dimensional muy potente y posee también funciones útiles para álgebra lineal, transformación de fourier y números aleatórios.

La principal ventaja de emplear Numpy en vez de las estructuras de datos nativas de Python es su eficiencia (rapidez), dado que ofrece nuevos tipos de variables que permiten generar expresiones vectorizadas, para las cuales hay funciones *precompiladas*, y escritas en *C*, lo que las hace muy rápidas.

El elemento principal de Numpy es la clase **ndarray**. De esta forma se definen vectores y matrices n-dimensionales, y se pueden inicializar a partir de, por ejemplo, una lista. También se pueden generar matrices a partir de listas-de-listas, o utilizando diferentes funciones.

En el indexado, se mantiene la lógica de las listas: indices comienzan en 0, y se pueden utilizar *Slices*. El objeto ndarray tiene un tipo de dato **dtype** homogeneo, aunque realiza conversiones automáticas (por ejemplo al sumar enteros y flotantes)

# <mark>Creación de arrays</mark>

Ahora importamos `numpy`. Por convención se importa como `np`

In [1]:
import numpy as np

## `np.zeros`

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Para crear un array 2D, le pasamos a la función una tupla con el número deseado de filas y columnas:

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Terminología

* En NumPy, cada dimensión se conoce como **axis**.
* El número de ejes o **axis** nos da la dimensión (**Rank**) (el array anterior es bi-dimensional).
    * El tamaño del primer eje es 3, y del segundo 4.
* Una tupla con los tamaños de los ejes del array se denomina **shape**.
    * Por ejemplo **shape** de la matriz anterior es `(3, 4)`.
* El número total de elementos en el array se denomina **size** y es igual al producto del tamaño de los ejes(por ejemplo 3*4=12)

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.shape

(3, 4)

In [6]:
a.ndim  # len(a.shape)

2

In [7]:
a.size

12

## Arrays N-dimensional


In [8]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Tipo de dato
los arrays de numpy son de tipo `ndarray`:

In [9]:
type(np.zeros( (3,4)) )

numpy.ndarray

## `np.ones`


In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.full`
Crea un array del shape dado inicializado con el valor especificado.

In [11]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## `np.empty`
Crea un array sin inicializar(su contenido no es predecible como el contenido en memoria hasta ese instante):

In [12]:
np.empty((2,3))

array([[4.85294815e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

## np.array
Se puede inicializar un `ndarray` usando listas con la función `array`:

In [13]:
np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

## `np.arange`


In [14]:
np.arange(1, 5)

array([1, 2, 3, 4])

Funciona también con flotantes:

In [15]:
np.arange(1.0, 5.0)

array([1., 2., 3., 4.])

También se le puede pasar un paso como parámetro

In [16]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Sin embargo, cuando se trabaja con flotantes, el número exacto de elementos del array no siempre es predecible. Por ejemplo:

In [17]:
print(np.arange(0, 5/3, 1/3)) # dependiendo de errores de punto flotante el último valor será 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))


[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


## `np.linspace`
Por esta razón, generalmente es preferible utilizar la función `linspace` en lugar de `arange` cuando se trabaja con flotantes. La función `linspace` devuelve un array que contiene un número determinado de puntos distribuidos uniformemente entre dos valores (nótese que el valor máximo está *incluido*, al contrario que `arange`)

In [18]:
print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


## `np.rand` and `np.randn`
Hay varias funciones disponibles en el módulo `random` de NumPy para crear `ndarrays` inicializados con valores aleatorios. Por ejemplo, a continuación tenemos una matriz de 3x4 inicializada con valores aleatorios entre 0 y 1 (distribución uniforme).

In [19]:
np.random.rand(3,4)

array([[0.97508239, 0.78948109, 0.37062296, 0.65673549],
       [0.77665885, 0.48821389, 0.98289466, 0.21480449],
       [0.7050879 , 0.65073722, 0.15984983, 0.50075496]])

Matriz de 3x4 que contiene números aleatorios flotantes muestreados a partir de una distribución normal univarida (distribución gaussiana) de media 0 y varianza 1:

In [20]:
np.random.randn(3,4)

array([[ 0.56721257, -0.96368382,  0.46081402, -0.19624169],
       [ 0.96976735, -0.5645065 ,  0.38389872, -0.71308476],
       [ 0.00792147,  1.03811102,  1.40512687, -0.02552121]])

# Array data
## `dtype`
Los `ndarrays` de NumPy son muy eficientes en parte porque todos sus elementos deben tener el mismo tipo de dato (normalmente númerico).
Se puede comprobar el tipo de dato mediante el atributo `dtype`:

In [21]:
c = np.arange(1, 5)
print(c.dtype, c)

int64 [1 2 3 4]


In [22]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

float64 [1. 2. 3. 4.]


En lugar de dejar que NumPy interprete el tipo de dato a utilizar, se puede establecer explícitamente al crear una matriz usando el parámetro `dtype`:

In [23]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


Algunos tipos de datos incluidos con signo `int8`, `int16`, `int32`, `int64`, sin signo `uint8`|`16`|`32`|`64`, flotantes `float16`|`32`|`64` y complejos `complex64`|`128`.



# <mark>Reshaping (Redimensionar un array)</mark>
## In place
Cambiar la forma de un `ndarray` es tan simple como modificar su atributo `shape`. Sin embargo, el número total de elementos de la matriz (`size`) debe seguir siendo el mismo.

In [24]:
g = np.arange(24)
print(g)
print("Dimensión:", g.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Dimensión: 1


In [25]:
g.shape = (6, 4)
print(g)
print("Dimensión:", g.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Dimensión: 2


In [26]:
g.shape = (2, 3, 4)
print(g)
print("Dimensión:", g.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Dimensión: 3


## `reshape`
La función `reshape` devuelve un nuevo objeto `ndarray` que apunta a los *mismos* datos. Esto significa que la modificación de un array también modificará el otro.

In [27]:
g2 = g.reshape(4,6)
print(g2)
print("Dimensión:", g2.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Dimensión: 2


Se establece el elemento de la fila 1, columna 2 en 999.

In [28]:
g2[1, 2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

El elemento correspondiente en el array original también se modifica

In [29]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

## `ravel`
Por último, la función `ravel` devuelve un nuevo `ndarray` unidimensional que también apunta a los mismos datos:

In [30]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# Operaciones aritméticas
Todos los operadores aritméticos usuales (`+`, `-`, `*`, `/`, `//`, `**`, etc.) pueden ser utilizados con los `ndarray`s. Estos se aplican elemento a elemento (*elementwise*):

In [31]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

a + b  = [19 27 35 43]
a - b  = [ 9 19 29 39]
a * b  = [70 92 96 82]
a / b  = [ 2.8         5.75       10.66666667 20.5       ]
a // b  = [ 2  5 10 20]
a % b  = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


# Conditional operators

Los operadores condicionales también se aplican elemento a elemento.

In [32]:
m = np.array([20, -5, 30, 40])
m < [15, 16, 35, 36]

array([False,  True,  True, False])

# <mark>Funciones matemáticas y estadísticas</mark>

## Métodos de los `ndarray`

In [33]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

[[-2.5  3.1  7. ]
 [10.  11.  12. ]]
mean = 6.766666666666667


Este método calcula la media de todos los elementos en el `ndarray` sin importar la forma del array.

Aquí hay otros métodos útiles del `ndarray`:

In [34]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

min = -2.5
max = 12.0
sum = 40.6
prod = -71610.0
std = 5.084835843520964
var = 25.855555555555554


<mark>Estas funciones aceptan un argumento opcional `axis` que permite solicitar que la operación se realice sobre elementos a lo largo de un eje dado. Por ejemplo:</mark>


In [35]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
c.sum(axis=0) #Suma las matrices

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [37]:
c.sum(axis=1)  # suma las filas

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [38]:
c.sum(axis=2) #suma las columnas

array([[ 6, 22, 38],
       [54, 70, 86]])

También se puede aplicar sobre múltiples axis:

In [39]:
c.sum(axis=(0,2))  # Sobre matrices y columnas

array([ 60,  92, 124])

## Funciones universales

NumPy también proporciona funciones elementales rápidas llamadas *funciones universales*, o **ufunc**. Por ejemplo, `square`  devuelve un nuevo `ndarray` que es una copia del `ndarray` original, excepto que cada elemento está elevado al cuadrado:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

Otras funciones:

In [ ]:
print("ndarray original")
print(a)
for func in (np.abs, np.sqrt, np.exp, np.log, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))

## ufuncs Binarias


In [ ]:
a = np.array([1, -2, 3, 4])
b = np.array([2, 8, -1, 7])
np.add(a, b)  # a + b

In [ ]:
np.greater(a, b)  # a > b

In [ ]:
np.maximum(a, b)

In [ ]:
np.copysign(a, b) #toma el primer array y le asigna el signo del segundo

# <mark>Indexación de arrays</mark>



## Arrays unidimensionales

In [40]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [41]:
a[2:5]

array([ 3, 19, 13])

In [42]:
a[2:-1]

array([ 3, 19, 13,  7])

In [43]:
a[:2]

array([1, 5])

In [44]:
a[2::2]

array([ 3, 13,  3])

In [45]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

Podemos modificar lo elementos:

In [46]:
a[3]=999
a

array([  1,   5,   3, 999,  13,   7,   3])

También se puede modificar un slice:

In [47]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

⚠️ Los **slices** son vistas de los `ndarray` sobre el mismo buffer de datos. Esto significa que si creas una "slice" y lo modificas,

¡también vas a modificar el `ndarray` original!

In [48]:
a_slice = a[2:6]
a_slice[1] = 1000
a  # modifica el array original

array([   1,    5,  997, 1000,  999,    7,    3])

✅ Si se quiere una copia de los datos, se debe utilizar el método `copy`:

In [49]:
another_slice = a[2:6].copy()
another_slice

array([ 997, 1000,  999,    7])

In [50]:
another_slice[3] = 4000
print(another_slice)
print(a)

[ 997 1000  999 4000]
[   1    5  997 1000  999    7    3]


## <mark>Selección de elementos</mark>
Los ndarrays se pueden indexar tanto con valores binarios como con valores enteros para rescatar datos de interés.

In [56]:
v=np.arange(10).reshape((2,5)) * 10
print(v)

ind = (v > 50) & (v < 90) # &, and; |, or

print(ind)
# Y si queremos tener los índices numéricos (posiciones)?
# v[ind]

indx, indy = np.where(ind)

print(indx, indy)

# v[(indx,indy)]
print(v[indx[0],indy[0]])

[[ 0 10 20 30 40]
 [50 60 70 80 90]]
[[False False False False False]
 [False  True  True  True False]]
[1 1 1] [1 2 3]
60


## Arrays multidimensionales
Se pueden acceder de forma similar, proporcionando un índice o slice para cada axis, separados por comas:

In [57]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [58]:
b[1, 2]

14

In [59]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [60]:
b[:, 1]

array([ 1, 13, 25, 37])

⚠️ **Cuidado**: Ver la diferencia sutil de las siguientes expresiones

In [64]:
b[1, :]
b[1, :].shape

(12,)

In [65]:
b[1:2, :].shape


(1, 12)

<mark>La primera expresión retorna la fila 1 como un array unidimensional de shape `(12,)`, La segunda expresión retorna la misma fila como un array 2D de shape `(1, 12)`.</mark>

In [66]:
c = b[1, :].copy()
c

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [67]:
c = c[np.newaxis, :]
c

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [68]:
print(b[1, :].shape)
print(c.shape)

(12,)
(1, 12)


También se puede especificar una lista de índices

In [ ]:
b[(0,2), 2:5]

In [ ]:
b[:, (-1, 2, -1)]

Si se proporcionan múltiples índices, se obtiene una `ndarray` 1D que contiene los valores de los elementos en las coordenadas especificadas.

In [ ]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]  # b[-1, 5], b[2, 9], b[-1, 1] y b[2, 9]

## Dimensiones superiores


In [ ]:
c = b.reshape(4,2,6)
c

In [ ]:
c[2, 1, 4]

In [ ]:
c[2, :, 3]

Si se omite las coordenadas de uno de los ejes, se devolverán todos los elementos de los mismos:

In [ ]:
c[2, 1]  # c[2, 1, :]

## Ellipsis (`...`)
También se pueden escribir elipsis (`...`) para indicar que se incluyan todos los ejes no especificados.

In [ ]:
c[2, ...]  # c[2, :, :]

In [ ]:
c[2, 1, ...]  #c[2, 1, :]

In [ ]:
c[2, ..., 3]  # c[2, :, 3]

In [ ]:
c[..., 3]  # c[:, :, 3]

## Indexación con booleanos


In [ ]:
b = np.arange(48).reshape(4, 12)
b

In [ ]:
rows_on = np.array([True, False, True, False])
b[rows_on, :]  # b[(0, 2), :]

In [ ]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]  # columnas 1, 4, 7 and 10

In [ ]:
b[b % 3 == 1]

# Iterar

La iteración sobre un `ndarray`s es muy similar a la iteración sobre listas de python. Tenga en cuenta que la iteración sobre matrices multidimensionales se realiza con respecto al primer eje.

In [ ]:
c = np.arange(24).reshape(2, 3, 4)
c

In [ ]:
for m in c:
    print("Item:")
    print(m)

In [ ]:
for i in range(len(c)):  # len(c) == c.shape[0]
    print("Item:")
    print(c[i])

Si se quiere iterar sobre *todos* los elementos del `ndarray`, simplemente itere sobre el atributo `flat`:

In [ ]:
for i in c.flat:
    print("Item:", i)

# <mark>Stacking arrays<mark>

Primero creamos algunas matrices iniciales:

In [69]:
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
q2 = np.full((4,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [71]:
q3 = np.full((3,4), 3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

## `vstack`
Ahora los apilamos de forma vertical con `vstack`:

In [72]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [73]:
q4.shape

(10, 4)

Esto fue posible porque q1, q2 y q3 tienen todos el mismo número de columnas (las filas no son iguales, pero no pasa nada porque estamos apilando sobre ese eje).

## `hstack`
Ahora apilamos q1 y q3 horizontalmente usando `hstack`:

In [74]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [75]:
q5.shape

(3, 8)

Esto es posible porque q1 y q3 tienen 3 filas. Como q2 tiene 4 filas, no puede apilarse horizontalmente con q1 y q3:

In [76]:
try:
    q5 = np.hstack((q1, q2, q3))
except ValueError as e:
    print(e)

all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


## `concatenate`
La función `concatenate` apila matrices a lo largo de cualquier eje existente.

In [77]:
q7 = np.concatenate((q1, q2, q3), axis=0)  # equivalente a vstack
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [78]:
q7.shape

(10, 4)

Como podrás adivinar, `hstack` es equivalente a llamar a `concatenate` con `axis=1`.

## `stack`
La función `stack` apila arrays a lo largo de un nuevo eje. Todas las matrices deben tener la misma forma.

In [79]:
q8 = np.stack((q1, q3))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [80]:
q8.shape

(2, 3, 4)

# Splitting arrays
Split es lo contrario de stack. Por ejemplo, utilicemos la función `vsplit` para dividir una matriz verticalmente.

Primero vamos a crear una matriz de 6x4:

In [81]:
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Ahora dividámoslo en tres partes iguales, verticalmente:

In [82]:
r1, r2, r3 = np.vsplit(r, 3)
r1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
r2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
r3

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

También existe una función `split` que divide un array a lo largo de cualquier eje. Llamar a `vsplit` es equivalente a llamar a `split` con `axis=0`. También existe la función `hsplit`, equivalente a llamar a `split` con `axis=1`:

In [ ]:
r4, r5 = np.hsplit(r, 2)
r4

In [ ]:
r5

## Multiplicación de matrices
Vamos a crear dos matrices y ejecutar una [multiplicación de matrices](https://es.wikipedia.org/wiki/Multiplicaci%C3%B3n_de_matrices) utilizando el método `dot()`.

In [ ]:
n1 = np.arange(10).reshape(2, 5)
n1

In [ ]:
n2 = np.arange(15).reshape(5,3)
n2

In [ ]:
n1.dot(n2)

**Precaución**: como vimos antes, `n1*n2` no es una multiplicación de matrices, sino un producto elemento a elemento (también llamado [producto Hadamard](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)).